application:
  name: DevOpsSimulator
  version: 2.0.0-beta
  environment:
    development
  server:
    host:
    localhost
    port: 3000
    ssl_enabled:
    false
    hot_reload:
    true
  logging:
    level:
    DEBUG
    format:
    pretty
  development:
    mock_apis:
    true
    debug_mode:
    true